language: java

services:
  - mysql

build:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean verify

test:
  - mvn test -B

notifications:
  email:
    recipients:
      - a.redonda89@gmail.com
      - gil.maricruz@gmail.com
    on_success: always # default: change
    on_failure: always # default: always

after_success:
- mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=<c75deea85ba742219a4a61328ce58b15> -DapiToken=<c75deea85ba742219a4a61328ce58b15>